PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "MeterReadings" (
	"Id"	INTEGER,
	"AccountId"	INTEGER NOT NULL,
	"RecordedAt"	TEXT NOT NULL,
	"Value"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
COMMIT;
